### ISSUE TITLE
/%s/channel/?__a=1

### ISSUE THREAD

**Issue by novitae** [araekiel/instahunter#3]
Hey,
Just a suggestion:

One day i felt on an endpoint displaying the normal `/username/?__a=1`, but with a lower rate limit when using it without auths. It is: `/username/channel/?__a=1`

Hope it can help if you reach ratelimit on the normal `/user/?__a=1`

**Comment by shashwatah** [comment]
Hey novitae,
I switched to a different network to check the endpoint out and noted a couple of things:
- The data returned was almost exactly the same, except the 'profile_pic_url'.
- The rate limit on this endpoint is not very different from what it is on the original one.

I don't think it's worth switching to this endpoint, although what can be done is that, when the original endpoint is rate-limited, the app switches to this endpoint.

**Comment by novitae** [comment]
> I don't think it's worth switching to this endpoint, although what can be done is that, when the original endpoint is rate-limited, the app switches to this endpoint.

Yep this is what I meant

**Comment by shashwatah** [comment]
ohh ok then.
